Repository epam/badgerdoc, pull requests merged in 2022-12, with the labels that each got.

#98 fix: alembic migration conflict
  annotation/alembic/versions/71095b8e6343_add_extensive_coverage_parameter.py
  annotation/app/categories/services.py
  annotation/app/tasks/resources.py
  annotation/tests/test_post_job.py
  annotation/tests/test_validation.py
Labels: bug, priority

#106 test: fix tests related to the extensive coverage
  annotation/tests/conftest.py
  annotation/tests/test_post_job.py
  annotation/tests/test_validation.py
Labels: bug

#130 feat: add document categorytypeschema enum
  annotation/alembic/versions/e56cb55fde06_document_category_enum_type.py
  annotation/app/schemas/categories.py
Labels: priority

#132 fix: add document_link category type enum
  annotation/alembic/versions/f1a58d769aa2_document_link_category_enum_type.py
  annotation/app/schemas/categories.py
Labels: enhancement

#136 hotfix: document categories adjustments
  annotation/alembic/versions/9083dea3783e_make_document_categories_an_array_of_.py
  annotation/app/annotations/main.py
  annotation/app/annotations/resources.py
  annotation/app/models.py
  annotation/app/schemas/annotations.py
  annotation/tests/test_get_accumulated_revisions.py
  annotation/tests/test_post_annotation.py
  annotation/tests/test_validation.py
Labels: priority

#146 hotfix: save doc categories if empty annotation
  annotation/app/annotations/main.py
  annotation/tests/test_post_annotation.py
Labels: priority
