Repository epam/badgerdoc, pull requests merged in 2023-01, with the labels that each got.

#163 fix: taxon search bug on null value with the in operator
  lib/filter_lib/src/query_modificator.py
Labels: bug

#138 feat: agreement score for multiple annotators
  annotation/.env
  annotation/alembic/versions/7cc1ed83c309_compare_agreement_scores.py
  annotation/app/models.py
  annotation/app/schemas/__init__.py
  annotation/app/schemas/tasks.py
  annotation/app/tasks/resources.py
  annotation/app/tasks/services.py
  annotation/tests/conftest.py
  annotation/tests/test_compare_scores.py
  annotation/tests/test_finish_task.py
Labels: priority

#203 fix: finish validation task on failed pages bug
  annotation/app/annotations/main.py
  annotation/app/schemas/annotations.py
  annotation/app/tasks/resources.py
  annotation/tests/test_get_accumulated_revisions.py
  annotation/tests/test_get_annotation_for_particular_revision.py
  annotation/tests/test_get_pages_info.py
  annotation/tests/test_get_revisions_without_annotation.py
  annotation/tests/test_post_annotation.py
  annotation/tests/test_validation.py
  web/src/api/hooks/tasks.ts
  web/src/components/task/task-modal/task-validation-modal.tsx
  web/src/components/task/task-sidebar/task-sidebar.tsx
  web/src/connectors/task-annotator-connector/task-annotator-context.tsx
Labels: bug, priority

#272 README: local setup
  README.md
Labels: documentation, good first issue

#281 Feat: disable uploading files number limitation
  assets/src/routers/files_router.py
Labels: enhancement, back-end
